name: Build

on:
  push:
    branches:
      - "Dev-k8s"

jobs:
  Build:
    runs-on:
      - medvista-runner

    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        timeout-minutes: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 2

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.AWS_ECR_REGISTRY }}/hellow
          tags: |
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}
        timeout-minutes: 1

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AWS_ECR_REGISTRY }}
          username: ${{ vars.AWS_ECR_ACCESS_KEY_ID}}
          password: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        timeout-minutes: 1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        timeout-minutes: 10
